// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"Nunu_frame/internal/handler"
	"Nunu_frame/internal/repository"
	"Nunu_frame/internal/router"
	"Nunu_frame/internal/server"
	"Nunu_frame/internal/service"
	"Nunu_frame/pkg/app"
	"Nunu_frame/pkg/jwt"
	"Nunu_frame/pkg/log"
	"Nunu_frame/pkg/server/http"
	"github.com/google/wire"
	"github.com/spf13/viper"
)

// Injectors from wire.go:

func NewWire(viperViper *viper.Viper, logger *log.Logger) (*app.App, func(), error) {
	jwtJWT := jwt.NewJwt(viperViper)
	handlerHandler := handler.NewHandler(logger)
	db := repository.NewDB(viperViper, logger)
	repositoryRepository := repository.NewRepository(logger, db)
	transaction := repository.NewTransaction(repositoryRepository)
	serviceService := service.NewService(transaction, logger, jwtJWT)
	userRepository := repository.NewUserRepository(repositoryRepository)
	userService := service.NewUserService(serviceService, userRepository)
	userHandler := handler.NewUserHandler(handlerHandler, userService)
	labelRepository := repository.NewLabelRepository(repositoryRepository)
	labelService := service.NewLabelService(serviceService, labelRepository)
	labelHandler := handler.NewLabelHandler(handlerHandler, labelService)
	categoryRepository := repository.NewCategoryRepository(repositoryRepository)
	categoryService := service.NewCategoryService(serviceService, categoryRepository)
	categoryHandler := handler.NewCategoryHandler(handlerHandler, categoryService)
	subCategoryRepository := repository.NewSubCategoryRepository(repositoryRepository)
	subCategoryService := service.NewSubCategoryService(serviceService, subCategoryRepository)
	subCategoryHandler := handler.NewSubCategoryHandler(handlerHandler, subCategoryService)
	routerDeps := router.RouterDeps{
		Logger:             logger,
		Config:             viperViper,
		JWT:                jwtJWT,
		UserHandler:        userHandler,
		LabelHandler:       labelHandler,
		CategoryHandler:    categoryHandler,
		SubCategoryHandler: subCategoryHandler,
	}
	httpServer := server.NewHTTPServer(routerDeps)
	appApp := newApp(httpServer)
	return appApp, func() {
	}, nil
}

// wire.go:

var repositorySet = wire.NewSet(repository.NewDB, repository.NewRepository, repository.NewTransaction, repository.NewUserRepository, repository.NewLabelRepository, repository.NewCategoryRepository)

var serviceSet = wire.NewSet(service.NewService, service.NewUserService, service.NewLabelService, service.NewCategoryService)

var handlerSet = wire.NewSet(handler.NewHandler, handler.NewUserHandler, handler.NewLabelHandler, handler.NewCategoryHandler)

var serverSet = wire.NewSet(server.NewHTTPServer)

// build App
func newApp(
	httpServer *http.Server,

) *app.App {
	return app.NewApp(app.WithServer(httpServer), app.WithName("demo-server"))
}
